spring:
  h2:
    console:
      enabled: true
      path: /h2-console

# ?? AWS RDS? ?? ?? ?? ?
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
