spring:
  datasource:
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/capstone
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB  # 업로드할 수 있는 파일의 최대 크기 설정
      max-request-size: 10MB

  cloud:
    aws:
      s3:
        bucket: ${S3_BUCKET_NAME}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      region:
        static: ap-northeast-2

logging:
  level:
    org.apache.coyote.http11: trace
    org.springframework.web.multipart: debug