spring:
  h2:
    console:
      enabled: true
      path: /h2-console

# AWS RDS로 추후 세팅해야 함
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create

cloud:
  aws:
    s3:
      bucket: jeiucap-bucket
    credentials:
      access-key: ${access}
      secret-key: ${secret}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false